# Generated by Django 2.0.3 on 2018-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('url', models.URLField(verbose_name='Site URL')),
            ],
            options={
                'ordering': ['site_name'],
            },
        ),
    ]
